import type { Metadata } from "next";
import localFont from "next/font/local"
import "./globals.css";

const interFont = localFont({
  src: "./fonts/Inter/Inter-VariableFont_opsz,wght.ttf",
  variable: "--font-inter",
  weight: '400 700'
})

const playfairDisplayFont = localFont({
  src: "./fonts/Playfair_Display/PlayfairDisplay-VariableFont_wght.ttf",
  variable: "--font-playfairdisplay",
  weight: '100 400 700'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playfairDisplayFont.variable} ${interFont.variable}`}>
        {children}
      </body>
    </html>
  );
}
