import type { Metadata } from "next";
import localFont from "next/font/local"
import Link from "next/link";
import "./globals.css";

const interFont = localFont({
  src: "./fonts/Inter/Inter-VariableFont_opsz,wght.ttf",
  variable: "--font-inter",
  weight: '400 700'
})

const playfairDisplayFont = localFont({
  src: "./fonts/Playfair_Display/PlayfairDisplay-VariableFont_wght.ttf",
  variable: "--font-playfairdisplay",
  weight: '100 400 700'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${playfairDisplayFont.variable} ${interFont.variable}`}>
         <header>
          <div className="site-logo">Universo em Foco</div>
          <p>Explore o incrível mundo da astronomia e descubra segredos do cosmos através de artigos, imagens e muito mais!</p>
         <nav>
            <Link href={"/"}>Início</Link>
            {" | "}
            <Link href={"/blog"}>Blog</Link>
            {" | "}
            <Link href={"/loja"}>Loja</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
